defaults:
  - train: btl
  - test: btl
  - dataset: cub200
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/launcher: joblib
  - _self_

train.devices: schedule
only_test: False
fast_dev: False

hydra:
  run:
    dir: ./logs_beta/${train.setting}_${now:%m%d}_${now:%H%M%S}
  sweep:
    dir: logs_optuna/op_${train.setting}_${now:%m%d}_${now:%H%M%S}
    subdir: ${hydra.job.num}    
  sweeper:
    sampler:
      seed: 1234
    direction: maximize
    study_name: rcir
    storage: null
    n_trials: 20
    n_jobs: 4
    params:
      train.lr: tag(log, interval(1e-7, 1e-4))
      train.lr_gamma: choice(0.999, 0.99)




